In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

base_path = "/content/drive/MyDrive/SEMESTER 6/DATASET"

print(os.listdir(base_path))

['GOOGLE_MAPS', 'TIKTOK', 'Untitled0.ipynb']

In [ ]:
import os

gmaps_path = "/content/drive/MyDrive/SEMESTER 6/DATASET/GOOGLE_MAPS"

files = os.listdir(gmaps_path)

print("Jumlah file:", len(files))
print(files[:10])

Jumlah file: 30
['Masjid_Raya_Baiturrahman.csv', 'Museum_Tsunami_Aceh.csv', 'Museum_PLTD_Apung.csv', 'Kubah_Mesjid_Sisa_Tsunami.csv', 'Ulee_Lheue_Beach.csv', 'Pantai_Alue_Naga.csv', 'Putroe_Phang_Park.csv', 'Taman_Sari_Gunongan.csv', 'Kerkhoff_Poetjoet.csv', 'Museum_Aceh.csv']

In [ ]:
import pandas as pd
import os

gmaps_path = "/content/drive/MyDrive/SEMESTER 6/DATASET/GOOGLE_MAPS"

all_data = []

for file in os.listdir(gmaps_path):
    if file.endswith(".csv"):
        try:
            df = pd.read_csv(
                os.path.join(gmaps_path, file),
                sep=';',
                encoding='latin1'
            )

            all_data.append(df)

        except Exception as e:
            print("ERROR :", file)
            print(e)

gmaps_df = pd.concat(all_data, ignore_index=True)

print("Jumlah baris :", gmaps_df.shape[0])
print("Jumlah kolom :", gmaps_df.shape[1])

gmaps_df.head()

Jumlah baris : 2836
Jumlah kolom : 40

,title,stars,text,publishedAtDate,likesCount,name,reviewerNumberOfReviews,isLocalGuide,responseFromOwnerDate,responseFromOwnerText,...,reviewImageUrls/5,reviewImageUrls/6,reviewImageUrls/7,reviewImageUrls/8,reviewImageUrls/9,reviewImageUrls/10,reviewImageUrls/11,reviewImageUrls/12,reviewImageUrls/13,reviewImageUrls/14
0,Masjid Raya Baiturrahman,5,Masjid raya Baiturrahman Aceh Dibangun pada ma...,12/02/2026 11:32,0,Rahmat Hidayat,260,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Masjid Raya Baiturrahman,5,Masjid penuh sejarah bagi masyarakat terutama ...,15/01/2026 08:09,0,Su Gandi,165,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Masjid Raya Baiturrahman,5,"mashaAllah diijinkan untuk berkunjung kesini, ...",21/01/2026 01:30,1,Ratih Andriani,239,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Masjid Raya Baiturrahman,5,"Tiada kata selain Subhanallah, ini masjid bagu...",09/11/2025 18:43,0,Raden Diky Dermawan,803,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Masjid Raya Baiturrahman,5,"Setiap kali ke Aceh, wajib kesini, masjid ini ...",22/01/2026 18:04,0,fahrul rozi,72,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(gmaps_df.columns.tolist())

['title', 'stars', 'text', 'publishedAtDate', 'likesCount', 'name', 'reviewerNumberOfReviews', 'isLocalGuide', 'responseFromOwnerDate', 'responseFromOwnerText', 'originalLanguage', 'publishAt', 'rating', 'reviewId', 'reviewOrigin', 'reviewUrl', 'reviewerId', 'reviewerPhotoUrl', 'reviewerUrl', 'textTranslated', 'translatedLanguage', 'visitedIn', 'reviewContext/Sebaiknya buat reservasi', 'reviewContext/Waktu antrean', 'reviewContext/Waktu kunjungan', 'reviewImageUrls/0', 'reviewImageUrls/1', 'reviewImageUrls/2', 'reviewImageUrls/3', 'reviewImageUrls/4', 'reviewImageUrls/5', 'reviewImageUrls/6', 'reviewImageUrls/7', 'reviewImageUrls/8', 'reviewImageUrls/9', 'reviewImageUrls/10', 'reviewImageUrls/11', 'reviewImageUrls/12', 'reviewImageUrls/13', 'reviewImageUrls/14']

In [ ]:
gmaps_clean = gmaps_df[
    ['title', 'text', 'stars', 'publishedAtDate', 'likesCount']
].copy()

gmaps_clean['platform'] = 'Google Maps'

print(gmaps_clean.shape)

gmaps_clean.head()

(2836, 6)

,title,text,stars,publishedAtDate,likesCount,platform
0,Masjid Raya Baiturrahman,Masjid raya Baiturrahman Aceh Dibangun pada ma...,5,12/02/2026 11:32,0,Google Maps
1,Masjid Raya Baiturrahman,Masjid penuh sejarah bagi masyarakat terutama ...,5,15/01/2026 08:09,0,Google Maps
2,Masjid Raya Baiturrahman,"mashaAllah diijinkan untuk berkunjung kesini, ...",5,21/01/2026 01:30,1,Google Maps
3,Masjid Raya Baiturrahman,"Tiada kata selain Subhanallah, ini masjid bagu...",5,09/11/2025 18:43,0,Google Maps
4,Masjid Raya Baiturrahman,"Setiap kali ke Aceh, wajib kesini, masjid ini ...",5,22/01/2026 18:04,0,Google Maps

In [ ]:
print("Sebelum hapus:", len(gmaps_clean))

gmaps_clean = gmaps_clean.dropna(subset=['text'])

print("Sesudah hapus:", len(gmaps_clean))

Sebelum hapus: 2836
Sesudah hapus: 2270

In [ ]:
output_path = "/content/drive/MyDrive/SEMESTER 6/DATASET/google_maps_clean.csv"

gmaps_clean.to_csv(
    output_path,
    index=False,
    encoding='utf-8-sig'
)

print("Berhasil disimpan:", output_path)

Berhasil disimpan: /content/drive/MyDrive/SEMESTER 6/DATASET/google_maps_clean.csv

In [ ]:
import os

tiktok_path = "/content/drive/MyDrive/SEMESTER 6/DATASET/TIKTOK"

files = os.listdir(tiktok_path)

print("Jumlah file:", len(files))
print(files)

Jumlah file: 5
['TikTok_Masjid_Raya_Baiturrahman.csv', 'TikTok_Museum_Tsunami_Aceh.csv', 'TikTok_PLTD_Apung.csv', 'TikTok_Ulee_Lheue_Beach.csv', 'TikTok_Lampuuk_Beach.csv']

In [ ]:
import pandas as pd
import os

tiktok_path = "/content/drive/MyDrive/SEMESTER 6/DATASET/TIKTOK"

all_tiktok = []

for file in os.listdir(tiktok_path):
    if file.endswith(".csv"):

        try:
            df = pd.read_csv(
                os.path.join(tiktok_path, file),
                sep=';',
                encoding='latin1'
            )
        except:
            df = pd.read_csv(
                os.path.join(tiktok_path, file),
                sep=',',
                encoding='latin1'
            )

        destinasi = file.replace("TikTok_", "").replace(".csv", "")

        df["title"] = destinasi

        all_tiktok.append(df)

tiktok_df = pd.concat(all_tiktok, ignore_index=True)

print("Jumlah baris:", tiktok_df.shape[0])
print("Jumlah kolom:", tiktok_df.shape[1])

tiktok_df.head()

Jumlah baris: 468
Jumlah kolom: 10

,text,diggCount,replyCommentTotal,createTimeISO,uniqueId,videoWebUrl,uid,cid,avatarThumbnail,title
0,terimakasih atas vidio yang mahal ini. kami sa...,176,9,20/05/2026 11:07,snstoreaffiliate,https://www.tiktok.com/@mainvisual.id/video/76...,"7,4359E+18","7,64182E+18",https://p16-common-sign.tiktokcdn-us.com/tos-a...,Masjid_Raya_Baiturrahman
1,Alhamdulillah sdh dpt masuk dan solat maghrib ...,46,1,20/05/2026 20:25,ummi_faqih63,https://www.tiktok.com/@mainvisual.id/video/76...,"7,01019E+18","7,64196E+18",https://p19-common-sign.tiktokcdn-us.com/tos-u...,Masjid_Raya_Baiturrahman
2,alhamdulillah,8,2,22/05/2026 12:44,janganjaditai,https://www.tiktok.com/@mainvisual.id/video/76...,"7,53512E+18","7,64259E+18",https://p19-common-sign.tiktokcdn-us.com/tos-a...,Masjid_Raya_Baiturrahman
3,Masha Allah ??,0,2,01/06/2026 09:44,erlinasweetgirl26,https://www.tiktok.com/@mainvisual.id/video/76...,"6,87474E+18","7,64625E+18",https://p16-common-sign.tiktokcdn-us.com/tos-a...,Masjid_Raya_Baiturrahman
4,ya Allah pengen sekali berkunjung ke masjid ra...,16,10,20/05/2026 19:36,izlfhmy,https://www.tiktok.com/@mainvisual.id/video/76...,"6,68523E+18","7,64195E+18",https://p19-common-sign.tiktokcdn-us.com/tos-a...,Masjid_Raya_Baiturrahman

In [ ]:
tiktok_clean = pd.DataFrame()

tiktok_clean["title"] = tiktok_df["title"]
tiktok_clean["text"] = tiktok_df["text"]

# TikTok tidak punya rating bintang
tiktok_clean["stars"] = None

# tanggal komentar
tiktok_clean["publishedAtDate"] = tiktok_df["createTimeISO"]

# jumlah like komentar
tiktok_clean["likesCount"] = tiktok_df["diggCount"]

# platform
tiktok_clean["platform"] = "TikTok"

print(tiktok_clean.shape)

tiktok_clean.head()

(468, 6)

,title,text,stars,publishedAtDate,likesCount,platform
0,Masjid_Raya_Baiturrahman,terimakasih atas vidio yang mahal ini. kami sa...,None,20/05/2026 11:07,176,TikTok
1,Masjid_Raya_Baiturrahman,Alhamdulillah sdh dpt masuk dan solat maghrib ...,None,20/05/2026 20:25,46,TikTok
2,Masjid_Raya_Baiturrahman,alhamdulillah,None,22/05/2026 12:44,8,TikTok
3,Masjid_Raya_Baiturrahman,Masha Allah ??,None,01/06/2026 09:44,0,TikTok
4,Masjid_Raya_Baiturrahman,ya Allah pengen sekali berkunjung ke masjid ra...,None,20/05/2026 19:36,16,TikTok

In [ ]:
print("Sebelum hapus:", len(tiktok_clean))

tiktok_clean = tiktok_clean.dropna(subset=["text"])

print("Sesudah hapus:", len(tiktok_clean))

Sebelum hapus: 468
Sesudah hapus: 466

In [ ]:
tiktok_clean.to_csv(
    "/content/drive/MyDrive/SEMESTER 6/DATASET/tiktok_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Berhasil disimpan")

Berhasil disimpan

In [ ]:
final_df = pd.concat(
    [gmaps_clean, tiktok_clean],
    ignore_index=True
)

print("Total data:", final_df.shape)

Total data: (2736, 6)

In [ ]:
final_df.to_csv(
    "/content/drive/MyDrive/SEMESTER 6/DATASET/final_dataset_wisata_banda_aceh.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset final berhasil disimpan")

Dataset final berhasil disimpan

In [ ]:
final_df["platform"].value_counts()

platform
Google Maps    2270
TikTok          466
Name: count, dtype: int64

In [ ]:
final_df["title"].nunique()

35

In [24]:
sorted(final_df["title"].unique())

['Air Terjun Kuta Malaka',
 'Benteng Kerajaan Aceh Lamuri - Indrapatra kampung ladong pungli',
 'Bukit Lamreh',
 'Bustanussalatin Central Park',
 'Desa Wisata Nusa, Aceh',
 'Hutan Kota BNI',
 'Kerkhoff Poetjoet',
 'Kolam Renang Mata Ie',
 'Kubah Mesjid Sisa Tsunami',
 'Lampuuk_Beach',
 'Masjid Baiturrahim - Ulee Lheue',
 'Masjid Haji Keuchik Leumiek',
 'Masjid Raya Baiturrahman',
 'Masjid_Raya_Baiturrahman',
 'Museum Aceh',
 'Museum PLTD Apung',
 'Museum Tsunami Aceh',
 'Museum_Tsunami_Aceh',
 'Nol Kilometer Kota Banda Aceh',
 'PLTD_Apung',
 'Pantai Alue Naga',
 'Pantai Lampuuk',
 'Pantai Lhoknga',
 'Pantai Lhokseudu',
 'Pantai Pasir Putih | Lhok Mee',
 'Pantai Rinting',
 'Pantai Syiah Kuala',
 'Pantai Ujong Batee',
 'Pantai Ulee Lheue',
 'Pantai cemara leupung',
 'Taman Krueng Neng Lamjamee',
 'Taman Putroe Phang',
 'Taman Sari Gunongan',
 'Ulee_Lheue_Beach',
 'Wahana Impian Malaka 69']

In [25]:
final_df["title"] = final_df["title"].replace({
    "Masjid_Raya_Baiturrahman": "Masjid Raya Baiturrahman",
    "Museum_Tsunami_Aceh": "Museum Tsunami Aceh",
    "PLTD_Apung": "Museum PLTD Apung",
    "Ulee_Lheue_Beach": "Pantai Ulee Lheue",
    "Lampuuk_Beach": "Pantai Lampuuk"
})

print("Jumlah destinasi unik =", final_df["title"].nunique())

Jumlah destinasi unik = 30

In [26]:
final_df.to_csv(
    "/content/drive/MyDrive/SEMESTER 6/DATASET/final_dataset_wisata_banda_aceh.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset final diperbarui")

Dataset final diperbarui